Initial commit
alibabacloud-automation/terraform-alicloud-clickhouse pull request #1
Opened 2022-03-23 02:41 UTC by bzran

2022-03-23 08:41 UTC, xiaozhu36 requested changes

2022-03-23 08:41 UTC, xiaozhu36 commented on README-CN.md
> +  vswitch_id              = "vsw-8vbctw4vi6jrcs75wgt89"
这个地方最好用一个假的vswitch ID，比如 vsw-abc12345

2022-03-23 08:41 UTC, xiaozhu36 commented on README.md
> +  vswitch_id              = "vsw-8vbctw4vi6jrcs75wgt89"
这个也一样

2022-03-23 08:41 UTC, xiaozhu36 commented on examples/complete/tfvars/01-update.tfvars
> +account_description = "tf-test-update-clickhouse-account"
可以修改的参数只有这两个么？

2022-03-23 08:41 UTC, xiaozhu36 commented on main.tf
> +  db_cluster_version      = var.db_cluster_version
对于每个资源，要增加一个是否创建的开关来控制是否要创建该资源，可以参考：https://github.com/terraform-alicloud-modules/terraform-alicloud-cloud-sso/blob/main/main.tf#L19

2022-03-23 08:41 UTC, xiaozhu36 commented on variables.tf
> +variable "db_cluster_network_type" {
如果只有一个枚举值，那么这个参数可以不用暴露出来，直接main.tf 中写死就好了

2022-03-23 08:41 UTC, xiaozhu36 commented on variables.tf
> +  default     = ""
对于这种有枚举值的，默认值设置为其中一个枚举值就行

2022-03-23 08:41 UTC, xiaozhu36 commented on versions.tf
> +terraform {
统一改成 ：

terraform {
  required_version = ">=0.13"
}

2022-03-23 14:15 UTC, bzran commented on README-CN.md
> +  vswitch_id              = "vsw-8vbctw4vi6jrcs75wgt89"
Done

2022-03-23 14:16 UTC, bzran commented on README.md
> +  vswitch_id              = "vsw-8vbctw4vi6jrcs75wgt89"
Done

2022-03-23 14:18 UTC, bzran commented on examples/complete/tfvars/01-update.tfvars
> +account_description = "tf-test-update-clickhouse-account"
Done，可以修改的属性已补上，其余属性为不可改

2022-03-23 14:18 UTC, bzran commented on main.tf
> +  db_cluster_version      = var.db_cluster_version
Done

2022-03-23 14:19 UTC, bzran commented on variables.tf
> +variable "db_cluster_network_type" {
Done

2022-03-23 14:19 UTC, bzran commented on variables.tf
> +  default     = ""
Done

2022-03-23 14:20 UTC, bzran commented on versions.tf
> +terraform {
Done

2022-03-24 03:33 UTC, xiaozhu36 requested changes

2022-03-24 03:33 UTC, xiaozhu36 commented on variables.tf
> +  default     = true
开关的默认值统一设置为 false

2022-03-24 05:04 UTC, merged