resource/alicloud_click_house_db_cluster: support attributes for encryption and period; resource/alicloud_click_house_account: support attributes for authority
alibabacloud-automation/terraform-alicloud-clickhouse pull request #6
Opened 2024-03-27 02:53 UTC by shanye997

2024-04-07 08:01 UTC, xiaozhu36 requested changes

2024-04-07 08:01 UTC, xiaozhu36 commented on main.tf
> +  used_time               = var.used_time
新增加的预付费的参数跟 spec 规范对齐吧，统一为 payment_type, payment_duration 和 payment_duration_unit

2024-04-07 08:01 UTC, xiaozhu36 commented on variables.tf
> +  type        = string
这个参数的可选值有哪些

2024-04-07 09:17 UTC, shanye997 commented on main.tf
> +  used_time               = var.used_time
已更新

2024-04-07 09:17 UTC, shanye997 commented on variables.tf
> +  type        = string
已更新可选值，并添加 example

2024-04-08 02:30 UTC, xiaozhu36 requested changes

2024-04-08 02:30 UTC, xiaozhu36 commented on variables.tf
> +    error_message = "Allowed values are CloudDisk"
这个message的语法不对吧

2024-04-08 02:30 UTC, xiaozhu36 commented on variables.tf
> +  type        = string
encryption_type 和 encryption_key 的关系是啥

2024-04-08 02:30 UTC, xiaozhu36 commented on variables.tf
> +  description = "Pre-paid cluster of the pay-as-you-go cycle. It is valid and required when payment_type is `Subscription`. Valid values: `Month`, `Year`."
这个描述写的不对吧

2024-04-08 02:30 UTC, xiaozhu36 commented on variables.tf
> +  description = "(Optional, ForceNew) The used time of DBCluster. It is valid and required when payment_type is `Subscription`."
既然这两个参数只在 Subscription的时候生效，那么在模板中是不是需要条件控制一下

2024-04-08 02:30 UTC, xiaozhu36 commented on variables.tf
> +  default     = ""
vpc_id 和 vswitch id 现在应该都是必填的了，可以测试下

另外，针对参数的是否必填，可以沉淀为 example 的测试规范

2024-04-08 02:45 UTC, shanye997 commented on variables.tf
> +  description = "Pre-paid cluster of the pay-as-you-go cycle. It is valid and required when payment_type is `Subscription`. Valid values: `Month`, `Year`."
当指定 encryption_type 时，encryption_key 必填

2024-04-08 03:15 UTC, shanye997 commented on variables.tf
> +  default     = ""
这个还是选填的，这个是新加的属性，必填的话之前测试就都不会通过了

2024-04-08 05:45 UTC, shanye997 commented on variables.tf
> +  description = "Pre-paid cluster of the pay-as-you-go cycle. It is valid and required when payment_type is `Subscription`. Valid values: `Month`, `Year`."
已更新描述

2024-09-05 02:03 UTC, closed without merging